### ISSUE TITLE
Add expected's mutex unlock call in case the Exec query doesn't match

### ISSUE THREAD

**Issue by portikCoder** [srikanthccv/ClickHouse-go-mock#22]
Hi

Thanks for the lib! I just realised in case the test suite is failing with the following schema:

1. expect: succeeds
2. expect: [fails with](https://github.com/srikanthccv/ClickHouse-go-mock/blob/406ec00fd785a6ed31fecc2b1ce68ea465f38f2b/clickconnmock.go#L409) `"call to database Exec with unexpected query: %s"`
3. expect: would have succeeded

but when I'm using `mock.ExpectationsWereMet()` the 2nd expectation is just locked up so is waiting forever on the other one.

Nothing but a simple `expected.Unlock()` is missed. A PR is coming as we discussed in the email.

**Comment by srikanthccv** [comment]
Thank you @portikCoder!

**Comment by portikCoder** [comment]
Please, do approve whenever u have the time. The fix is mentioning this issue for the record.

**Comment by srikanthccv** [comment]
Thanks!
